In [1]:
import pandas as pd

file_path = 'data/vgsales.csv'
df = pd.read_csv(file_path)

df.head(10)

df.tail(5)

df.info()

df.describe()

df.dtypes

df['Genre'].value_counts()

df['Platform'].unique()

df[df['NA_Sales'] > 1]

df[df['JP_Sales'] < 0.1]

df.query("Genre == 'Action' and Global_Sales > 2")

df[['Name', 'Global_Sales']]

df.loc[5:10, ['Name', 'Genre']]

df.iloc[:5, :3]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

   Rank                      Name Platform
0     1                Wii Sports      Wii
1     2         Super Mario Bros.      NES
2     3            Mario Kart Wii      Wii
3     4         Wii Sports Resort      Wii
4     5  Pokemon Red/Pokemon Blue       GB